Download the MNIST dataset for multiclass classification of handwritten digits. Implement the kernel Perceptron from scratch and run it to train 10 binary classifiers, one for each of the 10 digits (one-vs-all encoding), using the polynomial kernel. In order to extract a binary classifier, do the following: run the algorithm for a given number of epochs (e.g., cycles over the entire training data) on a random permutation of the training set and collect the ensemble of predictorsused by the Perceptron when predicting each training datapoint . Then use:

- the average of the predictors in the ensemble;
- the predictor achieving the smallest training error among those in the ensemble.

Based on the given split of the data in training and test set, evaluate the multiclass classification performance (zero-one loss) for different values of the number of epochs (go up to at least 10 epochs) and the degree of the polynomial (go up to at least degree 6). In order to use the 10 binary classifiers to make multiclass predictions, use the fact that binary classifiers trained by the Perceptron have the form _argmax gixi_ and predict using  wherecorresponds to the binary classifier for class.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [2]:
#dataset MNIST
dataset = pd.read_csv("mnist_test.csv")
dataset.head(10)

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...      0      0   
1      2    0    0    0    0    0    0    0    0    0  ...      0      0   
2      1    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      4    0    0    0    0    0    0    0    0    0  ...      0      0   
5      1    0    0    0    0    0    0    0    0    0  ...      0      0   
6      4    0    0    0    0    0    0    0    0    0  ...      0      0   
7      9    0    0    0    0    0    0    0    0    0  ...      0      0   
8      5    0    0    0    0    0    0    0    0    0  ...      0      0   
9      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  
5      0      0      0      0      0      0      0      0  
6      0      0      0      0      0      0      0      0  
7      0      0      0      0      0      0      0      0  
8      0      0      0      0      0      0      0      0  
9      0      0      0      0      0      0      0      0  

[10 rows x 785 columns]

In [3]:
#divide the data domain from the label set 
X = dataset.drop(["label"], axis =1).values

In [4]:
#look at the data domain
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [5]:
#extracting the label set 
Y = dataset[["label"]].values

In [6]:
#train and test split 
np.random.seed(67)
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.4, stratify = Y)

In [7]:
y_train

array([[5],
       [9],
       [6],
       ...,
       [6],
       [0],
       [2]])

In [8]:
#Apply OneHotEncoder
encoder = OneHotEncoder(sparse=False)

In [9]:
#apply the one-hot encoder at the train 
y_train = encoder.fit_transform(y_train)

/Users/margheritamaroni/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


Since we have a binary label set {-1, 1}, we want the 0 to become -1.


In [10]:
y_train[y_train == 0] = -1

In [11]:
y_train

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1.,  1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ...,
       [-1., -1., -1., ..., -1., -1., -1.],
       [ 1., -1., -1., ..., -1., -1., -1.],
       [-1., -1.,  1., ..., -1., -1., -1.]])

In [12]:
y_train[100,:]

array([-1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.])

In [13]:
y_train[100,:].argmax() 
#come farò la predizione in multiclass classification

5

In [14]:
y_train.shape
#6000 observations for 10 columns

(6000, 10)


# Polynomial kernel

In [15]:
#(1+np.dot(x_train[0], x_train[0]))**2

In [16]:
#(1+(x_train[0].T@ x_train[0]))**2

In [17]:
#Create the matrix for degree = 2

In [18]:
#inizializza la matrice vuota
#Kernel = np.zeros((6000, 6000))
#for column in range(6000):
    #for row in range(6000):
        #Kernel[row,column] = (1+(x_train[row].T@ x_train[column]))**2

In [19]:
#np.savetxt("First_Matrix.txt", Kernel, delimiter = ",")

In [20]:
matrix_d2= pd.read_csv("First_Matrix.txt", header = None)

In [21]:
matrix_d2 = matrix_d2.to_numpy()

In [22]:
matrix_d2[:,1]

array([2.79642006e+12, 3.29519051e+13, 4.97080848e+12, ...,
       6.35680746e+12, 1.67279119e+13, 7.74064797e+12])

In [23]:
matrix_d2[1,:]

array([2.79642006e+12, 3.29519051e+13, 4.97080848e+12, ...,
       6.35680746e+12, 1.67279119e+13, 7.74064797e+12])

In [24]:
matrix_d2[:,1]

array([2.79642006e+12, 3.29519051e+13, 4.97080848e+12, ...,
       6.35680746e+12, 1.67279119e+13, 7.74064797e+12])

In [25]:
y_train[:,0],len(y_train[:,0])

(array([-1., -1., -1., ..., -1.,  1., -1.]), 6000)

In [26]:
matrix_d2[:1] * y_train[:,0] 

array([[-3.09689134e+13, -2.79642006e+12, -8.93417480e+12, ...,
        -9.18650636e+12,  5.12969047e+12, -5.52372677e+12]])

In [27]:
np.sum(matrix_d2[:,1] * y_train[:,0])

-2.4782617494320576e+16

In [28]:
np.sign(np.sum(matrix_d2[:,1] * y_train[:,0]))

-1.0

In [29]:
#Five epochs
S5 =np.zeros((6000,10))
for digit in range(10):
    for epoch in range(5):
        y_pred = np.zeros(6000)
        for point in range(6000):
            y_pred[point]= np.sign(np.sum(matrix_d2[:,point] * y_train[:,digit] * S5[:,digit]))

        for point in range(6000):
            if y_pred[point] != y_train[point,digit]:
                S5[point,digit]+=1

In [30]:
#np.savetxt("S5_d2_e5.txt", S5,  delimiter = ",")

In [31]:
S5_d2_e5 = pd.read_csv("S5_d2_e5.txt", header = None)
S5_d2_e5

0    1    2    3    4    5    6    7    8    9
0     1.0  1.0  1.0  1.0  1.0  5.0  1.0  1.0  1.0  1.0
1     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  5.0
2     1.0  1.0  1.0  1.0  1.0  1.0  5.0  1.0  1.0  1.0
3     1.0  1.0  1.0  4.0  1.0  1.0  1.0  1.0  1.0  1.0
4     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  5.0  1.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
5995  1.0  1.0  1.0  1.0  1.0  1.0  1.0  5.0  1.0  1.0
5996  1.0  1.0  1.0  1.0  1.0  1.0  1.0  5.0  1.0  1.0
5997  1.0  1.0  1.0  1.0  1.0  1.0  4.0  1.0  1.0  1.0
5998  3.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
5999  1.0  1.0  4.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

[6000 rows x 10 columns]

In [32]:
np.unique(S5[:,0],return_counts = True)

(array([1., 2., 3., 4., 5.]), array([5398,   11,  311,  132,  148]))

In [33]:
#Prediction for the training set
pred = np.zeros((6000,10))
for digit in range(10):
    for point in range(6000):
        pred[point,digit] = np.sign(np.sum(matrix_d2[:,point]*y_train[:,digit]*S5[:,digit]))


In [34]:
pred[:,0]

array([-1., -1., -1., ..., -1.,  1., -1.])

In [35]:
y_train[:,0]

array([-1., -1., -1., ..., -1.,  1., -1.])

we need to look if these two columns correspond


In [36]:
matrix_training_error = np.zeros((6000,10))

In [37]:
for point in range(6000):
    for digit in range(10):
        if pred[point,digit] != y_train[point,digit]:
            matrix_training_error[point, digit] = 1

In [38]:
matrix_training_error

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
matrix_training_error[:,0]

array([0., 0., 0., ..., 0., 0., 0.])

I'm going to compute the training error for each digit of my matrix of degree = 2 for 10 epochs

In [40]:
a = np.mean(matrix_training_error[:,0])
a

0.023833333333333335

In [41]:
b = np.mean(matrix_training_error[:,1])
b

0.0475

In [42]:
c = np.mean(matrix_training_error[:,2])
c

0.052

In [43]:
d = np.mean(matrix_training_error[:,3])
d

0.04666666666666667

In [44]:
e = np.mean(matrix_training_error[:,4])
e

0.09133333333333334

In [45]:
f = np.mean(matrix_training_error[:,5])
f

0.08916666666666667

In [46]:
g = np.mean(matrix_training_error[:,6])
g

0.0345

In [47]:
h = np.mean(matrix_training_error[:,7])
h

0.05733333333333333

In [48]:
i = np.mean(matrix_training_error[:,8])
i 

0.0765

In [49]:
j = np.mean(matrix_training_error[:,9])
j

0.08733333333333333

In [50]:
#Training error for 5 epochs for 10 digits
five_epochs = np.array([a,b,c,d,e,f,g,h,i,j])
five_epochs

array([0.02383333, 0.0475    , 0.052     , 0.04666667, 0.09133333,
       0.08916667, 0.0345    , 0.05733333, 0.0765    , 0.08733333])

In [52]:
#Ten epochs
S10 =np.zeros((6000,10))
for epoch in range(10):
    for digit in range(10):
        y_pred = np.zeros(6000)
        for point in range(6000):
            y_pred[point]= np.sign(np.sum(matrix_d2[:,point] * y_train[:,digit] * S10[:,digit]))

        for point in range(6000):
            if y_pred[point] != y_train[point,digit]:
                S10[point,digit]+=1

In [53]:
#np.savetxt("S10_d2_e10.txt", S10, delimiter = ',')

In [54]:
S10_d2_e10 = pd.read_csv("S10_d2_e10.txt", header = None)
S10_d2_e10

0    1    2    3     4    5     6    7     8    9
0     0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
1     0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
2     0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
3     0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
4     0.0  0.0  0.0  0.0  10.0  0.0  10.0  0.0  10.0  0.0
...   ...  ...  ...  ...   ...  ...   ...  ...   ...  ...
5995  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
5996  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
5997  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
5998  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0
5999  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0

[6000 rows x 10 columns]

In [55]:
pred = np.zeros((6000,10))
for digit in range(10):
    for point in range(6000):
        pred[point,digit] = np.sign(np.sum(matrix_d2[:,point]*y_train[:,digit]*S10[:,digit]))

In [56]:
matrix_training_error = np.zeros((6000,10))

In [57]:
for point in range(6000):
    for digit in range(10):
        if pred[point,digit] != y_train[point,digit]:
            matrix_training_error[point,digit] = 1

In [58]:
ten_epochs = []
for numero in range(10):
    ten_epochs.append(np.mean(matrix_training_error[:,numero]))

In [59]:
ten_epochs

[0.019333333333333334,
 0.0155,
 0.032,
 0.03883333333333333,
 0.03766666666666667,
 0.044,
 0.021666666666666667,
 0.022833333333333334,
 0.059333333333333335,
 0.06566666666666666]

In [60]:
ten_epochs = np.array(ten_epochs)

In [61]:
#Training error for 10 epochs and 10 digits
ten_epochs

array([0.01933333, 0.0155    , 0.032     , 0.03883333, 0.03766667,
       0.044     , 0.02166667, 0.02283333, 0.05933333, 0.06566667])

In [62]:
#Fifteen epochs
S15 =np.zeros((6000,10))
for epoch in range(15):
    for digit in range(10):
        y_pred = np.zeros(6000)
        for point in range(6000):
            y_pred[point]= np.sign(np.sum(matrix_d2[:,point] * y_train[:,digit] * S15[:,digit]))

        for point in range(6000):
            if y_pred[point] != y_train[point,digit]:
                S15[point,digit]+=1

In [63]:
#np.savetxt("S15_d2_e15.txt", S15, delimiter = ',')

In [64]:
S15_d2_e15 = pd.read_csv("S15_d2_e15.txt", header = None)
S15_d2_e15

0    1    2     3    4    5     6    7     8     9
0     1.0  1.0  1.0  10.0  1.0  8.0   1.0  1.0   1.0   1.0
1     1.0  1.0  1.0   1.0  1.0  1.0   1.0  1.0   1.0  12.0
2     1.0  1.0  1.0   1.0  1.0  1.0   5.0  1.0   1.0   1.0
3     1.0  1.0  1.0   4.0  1.0  1.0   1.0  1.0   1.0   1.0
4     1.0  1.0  1.0   1.0  7.0  1.0  10.0  1.0  15.0   1.0
...   ...  ...  ...   ...  ...  ...   ...  ...   ...   ...
5995  1.0  1.0  1.0   1.0  1.0  1.0   1.0  6.0   1.0   1.0
5996  1.0  1.0  1.0   1.0  1.0  1.0   1.0  5.0   1.0   4.0
5997  1.0  1.0  1.0   1.0  1.0  1.0   4.0  1.0   1.0   1.0
5998  3.0  1.0  1.0   1.0  1.0  1.0   1.0  1.0   1.0   1.0
5999  1.0  1.0  4.0   1.0  1.0  1.0   1.0  1.0   1.0   1.0

[6000 rows x 10 columns]

In [65]:
pred = np.zeros((6000,10))
for digit in range(10):
    for point in range(6000):
        pred[point,digit] = np.sign(np.sum(matrix_d2[:,point]*y_train[:,digit]*S15[:,digit]))

In [66]:
matrix_training_error = np.zeros((6000,10))

In [67]:
for point in range(6000):
    for digit in range(10):
        if pred[point,digit] != y_train[point,digit]:
            matrix_training_error[point,digit] = 1

In [68]:
fifteen_epochs = []
for numero in range(10):
    fifteen_epochs.append(np.mean(matrix_training_error[:,numero]))

In [69]:
fifteen_epochs = np.array(fifteen_epochs)

In [70]:
#Training error for 15 epochs and 10 digits
fifteen_epochs

array([0.0165    , 0.00983333, 0.0285    , 0.03266667, 0.03033333,
       0.03216667, 0.02083333, 0.02183333, 0.04033333, 0.049     ])

In [71]:
#Twenty epochs
S20 =np.zeros((6000,10))
for epoch in range(20):
    for digit in range(10):
        y_pred = np.zeros(6000)
        for point in range(6000):
            y_pred[point]= np.sign(np.sum(matrix_d2[:,point] * y_train[:,digit] * S20[:,digit]))

        for point in range(6000):
            if y_pred[point] != y_train[point,digit]:
                S20[point,digit]+=1

In [72]:
#np.savetxt("S20_d2_e20.txt",S20, delimiter = ',')

In [73]:
S20_d2_e20 = pd.read_csv("S20_d2_e20.txt", header = None)
S20_d2_e20

0    1    2     3     4    5     6    7     8     9
0     1.0  1.0  1.0  11.0   1.0  8.0   1.0  1.0   1.0   1.0
1     1.0  1.0  1.0   1.0   1.0  1.0   1.0  1.0   1.0  12.0
2     1.0  1.0  1.0   1.0   1.0  1.0   5.0  1.0   1.0   1.0
3     1.0  1.0  1.0   4.0   1.0  1.0   1.0  1.0   1.0   1.0
4     1.0  1.0  1.0   1.0  12.0  1.0  15.0  1.0  20.0   1.0
...   ...  ...  ...   ...   ...  ...   ...  ...   ...   ...
5995  1.0  1.0  1.0   1.0   1.0  1.0   1.0  6.0   1.0   1.0
5996  1.0  1.0  1.0   1.0   1.0  1.0   1.0  5.0   1.0   4.0
5997  1.0  1.0  1.0   1.0   1.0  1.0   4.0  1.0   1.0   1.0
5998  3.0  1.0  1.0   1.0   1.0  1.0   1.0  1.0   1.0   1.0
5999  1.0  1.0  4.0   1.0   1.0  1.0   1.0  1.0   1.0   1.0

[6000 rows x 10 columns]

In [74]:
pred = np.zeros((6000,10))
for digit in range(10):
    for point in range(6000):
        pred[point,digit] = np.sign(np.sum(matrix_d2[:,point]*y_train[:,digit]*S20[:,digit]))

In [75]:
matrix_training_error = np.zeros((6000,10))

In [76]:
for point in range(6000):
    for digit in range(10):
        if pred[point,digit] != y_train[point,digit]:
            matrix_training_error[point,digit] = 1

In [77]:
twenty_epochs = []
for numero in range(10):
    twenty_epochs.append(np.mean(matrix_training_error[:,numero]))

In [78]:
twenty_epochs = np.array(twenty_epochs)

In [79]:
#Training error for 20 epochs and 10 digits
twenty_epochs

array([0.014     , 0.00866667, 0.02433333, 0.02566667, 0.02566667,
       0.02666667, 0.0185    , 0.02066667, 0.0345    , 0.03766667])

In [80]:
#Twenty_five epochs
S25 =np.zeros((6000,10))
for epoch in range(25):
    for digit in range(10):
        y_pred = np.zeros(6000)
        for point in range(6000):
            y_pred[point]= np.sign(np.sum(matrix_d2[:,point] * y_train[:,digit] * S25[:,digit]))

        for point in range(6000):
            if y_pred[point] != y_train[point,digit]:
                S25[point,digit]+=1

In [81]:
np.savetxt("S25_d2_e25.txt", S25, delimiter = ',')

In [82]:
S25_d2_e25 = pd.read_csv("S25_d2_e25.txt", header = None)
S25_d2_e25

0    1    2     3     4    5     6    7     8     9
0     1.0  1.0  1.0  11.0   1.0  8.0   1.0  1.0   1.0   1.0
1     1.0  1.0  1.0   1.0   1.0  1.0   1.0  1.0   1.0  12.0
2     1.0  1.0  1.0   1.0   1.0  1.0   5.0  1.0   1.0   1.0
3     1.0  1.0  1.0   4.0   1.0  1.0   1.0  1.0   1.0   1.0
4     1.0  1.0  1.0   1.0  17.0  1.0  20.0  1.0  25.0   1.0
...   ...  ...  ...   ...   ...  ...   ...  ...   ...   ...
5995  1.0  1.0  1.0   1.0   1.0  1.0   1.0  6.0   1.0   1.0
5996  1.0  1.0  1.0   1.0   1.0  1.0   1.0  5.0   1.0   4.0
5997  1.0  1.0  1.0   1.0   1.0  1.0   4.0  1.0   1.0   1.0
5998  3.0  1.0  1.0   1.0   1.0  1.0   1.0  1.0   1.0   1.0
5999  1.0  1.0  4.0   1.0   1.0  1.0   1.0  1.0   1.0   1.0

[6000 rows x 10 columns]

In [83]:
pred = np.zeros((6000,10))
for digit in range(10):
    for point in range(6000):
        pred[point,digit] = np.sign(np.sum(matrix_d2[:,point]*y_train[:,digit]*S25[:,digit]))

In [84]:
matrix_training_error = np.zeros((6000,10))

In [85]:
for point in range(6000):
    for digit in range(10):
        if pred[point,digit] != y_train[point,digit]:
            matrix_training_error[point,digit] = 1

In [86]:
twenty_five_epochs = []
for numero in range(10):
    twenty_five_epochs.append(np.mean(matrix_training_error[:,numero]))

In [87]:
twenty_five_epochs = np.array(twenty_five_epochs)

In [88]:
#training error for 25 epochs and 10 digits

In [89]:
twenty_five_epochs

array([0.0125    , 0.0075    , 0.021     , 0.023     , 0.022     ,
       0.02116667, 0.0155    , 0.018     , 0.02633333, 0.032     ])

In [90]:
rows= np.array([five_epochs, ten_epochs, fifteen_epochs, twenty_epochs, twenty_five_epochs])

In [91]:
index = ["five_epochs", "ten_epochs", "fifteen_epochs", "twenty_epochs", "twenty_five_epochs"] 

In [92]:
df = pd.DataFrame(rows, index = index)

In [93]:
df

0         1         2         3         4  \
five_epochs         0.023833  0.047500  0.052000  0.046667  0.091333   
ten_epochs          0.019333  0.015500  0.032000  0.038833  0.037667   
fifteen_epochs      0.016500  0.009833  0.028500  0.032667  0.030333   
twenty_epochs       0.014000  0.008667  0.024333  0.025667  0.025667   
twenty_five_epochs  0.012500  0.007500  0.021000  0.023000  0.022000   

                           5         6         7         8         9  
five_epochs         0.089167  0.034500  0.057333  0.076500  0.087333  
ten_epochs          0.044000  0.021667  0.022833  0.059333  0.065667  
fifteen_epochs      0.032167  0.020833  0.021833  0.040333  0.049000  
twenty_epochs       0.026667  0.018500  0.020667  0.034500  0.037667  
twenty_five_epochs  0.021167  0.015500  0.018000  0.026333  0.032000

**Salvo la matrice con tutti i training error per le 25 epoche, degree = 2**

In [94]:
#np.savetxt("training_error_degree_2.csv", df, delimiter = ",")

In [95]:
degree_2 = pd.read_csv("training_error_degree_2.csv", header = None)

In [96]:
degree_2

0         1         2         3         4         5         6  \
0  0.023833  0.047500  0.052000  0.046667  0.091333  0.089167  0.034500   
1  0.019333  0.015500  0.032000  0.038833  0.037667  0.044000  0.021667   
2  0.016500  0.009833  0.028500  0.032667  0.030333  0.032167  0.020833   
3  0.014000  0.008667  0.024333  0.025667  0.025667  0.026667  0.018500   
4  0.012500  0.007500  0.021000  0.023000  0.022000  0.021167  0.015500   

          7         8         9  
0  0.057333  0.076500  0.087333  
1  0.022833  0.059333  0.065667  
2  0.021833  0.040333  0.049000  
3  0.020667  0.034500  0.037667  
4  0.018000  0.026333  0.032000

In [97]:
import matplotlib.pyplot as plt
plt.plot(degree_2)
plt.grid()
plt.show()

<Figure size 640x480 with 1 Axes>

In [98]:
degree_2.iloc[:,0].values.argmin()

4

In [99]:
degree_2.iloc[:,1].values.argmin()

4

In [100]:
degree_2.iloc[:,2].values.argmin()

4

In [101]:
degree_2.iloc[:,3].values.argmin()

4

In [102]:
degree_2.iloc[:,4].values.argmin()

4

In [103]:
degree_2.iloc[:,5].values.argmin()

4

In [104]:
degree_2.iloc[:,6].values.argmin()

4

In [105]:
degree_2.iloc[:,7].values.argmin()

4

In [106]:
degree_2.iloc[:,8].values.argmin()

4

In [107]:
degree_2.iloc[:,9].values.argmin()

4

In [108]:
#25 epoch give the smallest training error for each digit
#S25 is the best predictor for each column (=digit)

# TEST 

In [109]:
test_error = np.zeros(4000)

In [110]:
for point in range(4000):
    y_pred = np.zeros(10)
    for digit in range(10):
        y_pred[digit] = np.sign(np.sum((1+np.dot(x_train[:,:], x_test[point,:]))**2
                *y_train[:,digit]*S25[:,digit]))
    if y_pred.argmax() != y_test[point]:
        test_error[point] = 1 #zero-one loss

In [111]:
np.mean(test_error)
#14.15% test error 

0.1415

In [112]:
S5[:]

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 5.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [3., 1., 1., ..., 1., 1., 1.],
       [1., 1., 4., ..., 1., 1., 1.]])

In [113]:
#Create a new predictor that is the average of the five previous predictors
average = np.zeros((6000,10))
average = average + np.array(S5[:]+S10[:]+S15[:]+S20[:]+S25[:]) 
average /= 5

In [114]:
average

array([[ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  1. , ...,  1. ,  1. , 10.2],
       [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
       ...,
       [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
       [ 3. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
       [ 1. ,  1. ,  4. , ...,  1. ,  1. ,  1. ]])

In [115]:
#np.savetxt("average_d2.txt", average, delimiter = ',')
pd.read_csv("average_d2.txt", header = None)

0    1    2    3    4    5     6    7     8    9
0     0.8  0.8  0.8  6.6  0.8  5.8   0.8  0.8   0.8  0.8
1     0.8  0.8  0.8  0.8  0.8  0.8   0.8  0.8   0.8  8.2
2     0.8  0.8  0.8  0.8  0.8  0.8   4.0  0.8   0.8  0.8
3     0.8  0.8  0.8  3.2  0.8  0.8   0.8  0.8   0.8  0.8
4     0.8  0.8  0.8  0.8  9.4  0.8  11.2  0.8  15.0  0.8
...   ...  ...  ...  ...  ...  ...   ...  ...   ...  ...
5995  0.8  0.8  0.8  0.8  0.8  0.8   0.8  4.6   0.8  0.8
5996  0.8  0.8  0.8  0.8  0.8  0.8   0.8  4.0   0.8  2.6
5997  0.8  0.8  0.8  0.8  0.8  0.8   3.2  0.8   0.8  0.8
5998  2.4  0.8  0.8  0.8  0.8  0.8   0.8  0.8   0.8  0.8
5999  0.8  0.8  3.2  0.8  0.8  0.8   0.8  0.8   0.8  0.8

[6000 rows x 10 columns]

In [116]:
test_error = np.zeros(4000)
for point in range(4000):
    y_pred = np.zeros(10)
    for digit in range(10):
        y_pred[digit] = np.sign(np.sum((1+np.dot(x_train[:,:], x_test[point,:]))**2
                *y_train[:,digit]*average[:,digit]))
    if y_pred.argmax() != y_test[point]:
        test_error[point] = 1 #zero-one loss

In [117]:
np.mean(test_error)
#24.45% test error

0.2385